---
exporters_system_group: "prom-exp"
exporters_system_user: "{{ exporters_system_group }}"

exporters_linux_bin_dir: '/opt/exporters'
exporters_linux_textfile_dir: '{{ exporters_linux_bin_dir }}/textfile'

exporters_install_list:
  - 'gaia-exporter'

exporters_linux_spec:
  - name: 'gaia-exporter'
    version: '1.0.0'
    port: '8080'
    type: bin
    file_config: true
