---
exporters_mirror: 'https://nexus.devops-spb.rnd.huawei.com/repository/devops-binaries/exporters'
exporters_consul_reg_acl_token: "{{ global_consul_reg_acl_token | default('FIXME') }}"
exporters_install_list:
  - 'node_exporter'

exporters_is_test: "{{ global_exporter_is_test | default('false') }}"
exporters_linux_spec:
  - name: 'pipelines_exporter'
    version: '0.3.4'
    port: ':9109'
    type: bin
    file_config: true




exporters_system_group: "prom-exp"
exporters_system_user: "{{ exporters_system_group }}"
exporter_elastic_user: "{{ global_elastic_monitoring | default({'user':'user', 'pass':'FIXME'}) }}"

exporters_linux_bin_dir: '/opt/exporters'
exporters_linux_textfile_dir: '{{ exporters_linux_bin_dir }}/textfile'


exporters_node_exporter_disabled_collectors: []

exporters_postgres_datasource: "user=postgres host=/patroni/data/ sslmode=disable"
exporters_dns_stats_port: "{{ global_dns_server_stats_port | default('8053') }}"

exporters_pipelines_gitlab_url: '{{ global_gitlab_green_url | default("https://rnd-gitlab-msc.huawei.com") }}'
exporters_pipelines_projects:
  - name: rus-os-team/virtual-machines-and-tools/panda
exporters_pipelines_token: '{{ vault_exporters_pipelines_token | default("FIXME") }}'
exporters_pipelines_fetch_pipeline_job_metrics: true
exporters_pipelines_fetch_pipeline_variables: true
exporters_pipelines_fetch_merge_request_pipelines_refs: true
exporters_pipelines_disable_tls_verify: false
exporters_stf_token: '{{ vault_exporters_stf_token | default("FIXME") }}'
exporters_stf_host: 'https://farm1.devops-spb.rnd.huawei.com'
