---
- name: Get port from configuration
  set_fact:
    single_port: "{{ item.port | default(false) }}"
    port_range: "{{ item.ports | default('null') }}"

- name: Set proper exporter port in fact
  set_fact:
    exporter_port: "{{ single_port | ternary(single_port,port_range[0].split(':')[0]) }}"

- name: Register {{ item.name }} in consul
  consul:
    host: 'localhost'
    port: 8500
    service_name: "{{ item.name }}"
    service_port: "{{ exporter_port }}"
    service_id: "{{ item.name }}:{{ inventory_hostname }}"
    interval: '15s'
    http: "{{ 'http://' + inventory_hostname + ':' + exporter_port + item.http_check | default('/') }}"
    token: "{{ exporters_consul_reg_acl_token }}"
    validate_certs: false
    state: "present"
    tags: "{{ group_names[0] }},{{ item.name }},{{ item.consul_extra_tags | default('') }}"
  when: not exporters_is_test
