---
- name: Find all temlates in {{ item.name }}
  set_fact:
    template_list: "{{ lookup('fileglob', 'templates/k8s/{{ item.name }}/*.yaml.j2', wantlist=True) }}"

- name: Apply resources from template to K8S
  k8s:
    state: present
    definition: "{{ lookup('template', inner_item)  | from_yaml }}"
    apply: true
    validate:
      fail_on_error: true
  loop: '{{ template_list }}'
  loop_control:
    loop_var: inner_item
